const selectableCities: string[] = [
    // ChatGPT generated https://chat.openai.com/share/0ebc4dbd-5261-403c-8803-747494fe5966
    "Ouagadougou",
    "São Tomé",
    "Kingstown",
    "Bishkek",
    "Juba",
    "Riga",
    "Paris",
    "London",
    "Tokyo",
    "Moscow",
    "Rabat",
    "Cairo",
    "Bucharest",
    "Lisbon",
    "Dili",
    "Addis Ababa",
    "Lusaka",
    "Singapore",
    "N'Djamena",
    "Copenhagen",
    "Athens",
    "Warsaw",
    "Beirut",
    "Paramaribo",
    "Brazzaville",
    "Tallinn",
    "Kigali",
    "Harare",
    "Ljubljana",
    "Yerevan",
    "Abuja",
    "Dublin",
    "Rome",
    "Hanoi",
    "Naypyidaw",
    "Pretoria",
    "Basseterre",
    "Niamey",
    "Banjul",
    "Madrid",
    "Andorra la Vella",
    "Monaco",
    "Kampala",
    "Beijing",
    "Luxembourg",
    "Phnom Penh",
    "Abu Dhabi",
    "Minsk",
    "Maseru",
    "Doha",
    "Kinshasa",
    "Nairobi",
    "Montevideo",
    "Muscat",
    "Dhaka",
    "Djibouti",
    "Berlin",
    "Bandar Seri Begawan",
    "Bangui",
    "Vienna",
    "Dodoma",
    "Victoria",
    "Tirana",
    "Honiara",
    "Caracas",
    "Dushanbe",
    "Apia",
    "Libreville",
    "Khartoum",
    "Kyiv",
    "Luanda",
    "Tashkent",
    "Bern",
    "Baku",
    "Bissau",
    "Kathmandu",
    "Ashgabat",
    "Bamako",
    "Freetown",
    "Bangkok",
    "Port of Spain",
    "Vilnius",
    "Praia",
    "Thimphu",
    "Lilongwe",
    "Castries",
    "Ulaanbaatar",
    "Gaborone",
    "Kabul",
    "Amman",
    "Oslo",
    "Kuala Lumpur",
    "Monrovia",
    "Pyongyang",
    "Windhoek",
    "Accra",
    "Lomé",
    "Nouakchott",
    "Tunis",
    "Zagreb",
    "Colombo",
    "New Delhi",
    "Port Vila",
    "Nicosia",
    "Vientiane",
    "Dakar",
    "Porto-Novo",
    "Asmara",
    "Sarajevo",
    "Port Louis",
    "Kuwait City",
    "Damascus",
    "Amsterdam",
    "Jakarta",
    "Antananarivo",
    "Prague",
    "Islamabad",
    "Reykjavik",
    "Mogadishu",
    "Malabo",
    "Tehran",
    "Vaduz",
    "Stockholm",
    "Chisinau",
    "Malé",
    "San Marino",
    "Bratislava",
    "Budapest",
    "Nukuʻalofa",
    "Taipei",
    "Podgorica",
    "Tripoli",
    "Maputo",
    "Manama",
    "Astana",
    "Baghdad",
    "Sofia",
    "Funafuti",
    "Conakry",
    "Belgrade",
    "Moroni",
    "Seoul",
    "Sana'a",
    "Washington, D.C.",
    "Algiers",
    "T'bilisi",
    "Bujumbura",
    "Valletta",
    "Brussels",
    "Ankara",
    "Helsinki",
    "Yaoundé",
    "Riyadh",
    "Manila",
];

export default selectableCities;
